### ISSUE TITLE
Demon King/Saint chances are broken

### ISSUE THREAD

**Issue by Cerxi** [WahyuYogo/Fantasy#3]
Rather than the 1% chance your comment says, your code is currently set to have a 15% chance of Demon King and Saint, but since they're both testing for 0-14 and Demon King is checked first, you have a 0% chance of Saint.

You should test <1 for Demon King and >99 for Saint, to get the intended outcome.

**Comment by lonewolfcoder2007** [comment]
Since he let the code is copy/paste from the previous block, I know that your concern is correct. However, the Math.random() * 100  function runs from 0 to 99, so we should set the demon king as 1, as you said, and saints to 98. I am working on it and I'm trying to bring back the ranking on my version

**Comment by NatsumeAoii** [comment]
bro didn't care much abt it, even my big update he didn't that care, so i revoke the PR, he just doin what he want, he doesn't care at all

**Comment by lonewolfcoder2007** [comment]
Yeah. I even make some good improvements like ranking, title and role, etc. He doesn't give an f. IF u wanna try it out, here's the link.
https://lonewolfcoder2007.github.io/Fantasy/

**Comment by NatsumeAoii** [comment]
nice improvements tho, also i'll make version of mine, which full of new role, race, etc

https://natsumeaoii.github.io/Fantasy-2.0/

here if u wanna to try it.

**Comment by lonewolfcoder2007** [comment]
That's a good one. MInd if I take some information like races, role and regions? I'm not particularly good at fantasy stuff (I am a military nerd). Maybe we can work together in this

**Comment by NatsumeAoii** [comment]
btw i doin huge upgrade for race, regions, faction, etc. so if you can't wait u i could fork urs so i could help something. im kinda huge fan with fantasy randomize things like this project, but sadly the dude was didn't care at all.

also if i could suggest u that u must make like the more modernize ver of this, i could help u with it

**Comment by lonewolfcoder2007** [comment]
Fo'sho. Will try to do a modernized ver of the fantasy. Imagine nukes, olasma, arc reactors, etc. (Which means say goodbye to the skills, though. I'm trying to keep the skills)
